### ISSUE TITLE
Fix hyphenated spliced directory purge attempt

### ISSUE THREAD

**Issue by durack1** [durack1/cmip5#28]
The code needs to be updated to prevent purge/rm attempts at the spliced `historical-rcp85` subdirs that are owned by @doutriaux1 - these subdirs are not updated as part of the xml scan.

```
** Generating new *.xml files **
rm: cannot remove `historical-rcp85/atm/mo/rsdt/cmip5.CESM1-WACCM.historical-rcp85.r3i1p1.mo.atm.Amon.rsdt.ver-v20130314.latestX.xml': Permission denied
rm: cannot remove `historical-rcp85/atm/mo/rsdt/cmip5.IPSL-CM5A-LR.historical-rcp85.r3i1p1.mo.atm.Amon.rsdt.ver-1.latestX.xml': Permission denied
...
```

**Comment by durack1** [comment]
@pochedls should this be reincarnated in cmiplib? If yes, I'll copy it across - it's likely a dupe of #41

**Comment by pochedls** [comment]
I don't think this will apply to new cmiplib.
