### ISSUE TITLE
creation_date and tracking_id global attributes

### ISSUE THREAD

**Issue by durack1** [durack1/cmip5#3]
There maybe some utility in capturing the creation_date and tracking_id global attributes of all or some of the files which the xmls span - these could be included in the YYMMDD_HHMMSS_list_outfiles.pickle file

**Comment by durack1** [comment]
@pochedls this is now implemented in your database right? therefore it's closed out here and no migrated

**Comment by pochedls** [comment]
I am not currently recording the tracking id or creation date (from the file header) in the database. So if you'd like this, we should migrate this ticket.

**Comment by durack1** [comment]
This will load up the time taken considerably, not sure it's worth it.. But we can chat about this

**Comment by durack1** [comment]
It's wrapped into the ***latest*** labelling, so you may have come up with another way of achieving the same thing in cmiplib..

**Comment by pochedls** [comment]
The idea I thought for this was to have a separate job that scans directories and runs something like trimModelList the updates the xml file names to denote the latest files (and the database).

**Comment by durack1** [comment]
Seems to me that why do things twice, when you can ascertain all the information, generate the filename and the xml in one step?

**Comment by durack1** [comment]
To compound this, what happens if you have a newer dataset and you ignore the earlier versions, but cdscan errors when it tries to write the xml, and then what happens? The logic I had was previously was to index ***EVERYTHING*** that can be, and then sort through the list of what you want after the fact
