### ISSUE TITLE
make_cmip5_xml.py - intelligent sort duplicates to prefer /data files

### ISSUE THREAD

**Issue by durack1** [durack1/cmip5#38]
Current duplicate removal is non-discriminatory - files contained in `/data` subdirs should be prioritized

Current paths scanned include:

```
/cmip5_css01/data/cmip5/
/cmip5_css01/scratch/cmip5/
/cmip5_css02/data/cmip5/
/cmip5_css02/scratch/cmip5/
/cmip5_gdo2/data/cmip5/
/cmip5_gdo2/scratch/cmip5/
/cmip5_css02/cmip5/data/cmip5/
/cmip5_css02/scratch/_gc/
```

```
From: "Ames, Sasha"
Date: Thursday, April 21, 2016 at 4:32 PM
To: "Durack , Paul J."
Subject: Re: removal of IPSL and INM duplicates on gdo2

Hi Paul,
It turns out that much of the data didn’t delete because permissions weren’t set and its owned
by a user who left the lab.  We’ll get that addressed.   As there’s nothing left on that that’s
not duplicated anyway, I’d suggest just removing that mount from your list of cdscans.  

Thanks,

Sasha
```

**Comment by durack1** [comment]
@pochedls should this be reincarnated in [cmiplib](https://github.com/durack1/cmiplib)? If yes, I'll copy it across

**Comment by pochedls** [comment]
I'm not totally sure what needs to be done here. But we can probably ignore this because we can make another list of duplicate directories.

**Comment by durack1** [comment]
This is a `data` vs `scratch` issue, so an attempt at trying to document some of the issues back in 2016, I agree, we can leave it dead as we have discussed this
